force-app/main/default/objects/Order_Created__e/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <label>Client Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Created__e/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Log__c/Order_Log__c.object-meta.xml
<CustomObject>
    <label>Order Log</label>
    <nameField>
        <label>Order Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Log__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Logs</relationshipLabel>
    <relationshipName>Order_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Log__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderCreatedTriggerHandlers.cls
public with sharing class OrderCreatedTriggerHandlers {
    public static void OrderCreatedEvent(List<Order_Created__e> newOrders) {
        List<Order_Log__c> orderLogs = new List<Order_Log__c>();

        for(Order_Created__e order : newOrders){
            Order_Log__c orderLog = new Order_Log__c();
            orderLog.ClientId__c = order.ClientId__c;
            orderLog.Price__c = order.Price__c;
            orderLog.Product_Name__c = order.Product_Name__c;
            orderLog.Quantity__c = order.Quantity__c;
            orderLog.Status__c = 'In Process';
            orderLog.Total_Price__c = order.Quantity__c * order.Price__c;

            orderLogs.add(orderLog);
        }

        if(!orderLogs.isEmpty()){
            insert orderLogs;
        }
    }
}